PERSONALITY_FLAVOR = {
    "friendly": {
        "greeting": "waves and smiles at you.",
        "talk": "is eager to chat.",
        "attack": "looks uncomfortable at the idea of fighting.",
        "inspect": "seems approachable and kind.",
        "after_ko": "will probably forgive you.",
        "rematch": "doesn't want to fight again.",
    },
    "grumpy": {
        "greeting": "grunts and barely acknowledges you.",
        "talk": "seems annoyed by conversation.",
        "attack": "looks ready to throw a punch.",
        "inspect": "looks irritable.",
        "after_ko": "will hold a grudge.",
        "rematch": "wants a rematch to get even.",
    },
    "timid": {
        "greeting": "looks away nervously.",
        "talk": "answers quietly and avoids eye contact.",
        "attack": "looks terrified.",
        "inspect": "seems shy and anxious.",
        "after_ko": "will avoid you from now on.",
        "rematch": "wants nothing to do with you.",
    },
    "aggressive": {
        "greeting": "sizes you up with a glare.",
        "talk": "talks in a confrontational tone.",
        "attack": "looks eager for a fight.",
        "inspect": "looks tough and dangerous.",
        "after_ko": "will definitely want a rematch.",
        "rematch": "demands a rematch!",
    },
    "forgiving": {
        "greeting": "greets you warmly.",
        "talk": "is happy to talk.",
        "attack": "tries to avoid conflict.",
        "inspect": "seems gentle.",
        "after_ko": "will forgive you.",
        "rematch": "doesn't want to fight again.",
    },
    "grudgeful": {
        "greeting": "glares at you suspiciously.",
        "talk": "answers with suspicion.",
        "attack": "looks like they're plotting revenge.",
        "inspect": "seems resentful.",
        "after_ko": "will never forget what you did.",
        "rematch": "wants a rematch to settle the score.",
    },
    "chatty": {
        "greeting": "greets you with a big smile and starts talking.",
        "talk": "can't stop talking.",
        "attack": "tries to talk you out of fighting.",
        "inspect": "seems very talkative.",
        "after_ko": "will talk about it to everyone.",
        "rematch": "would rather talk than fight.",
    },
    "quiet": {
        "greeting": "nods silently.",
        "talk": "doesn't say much.",
        "attack": "shrugs and prepares to defend.",
        "inspect": "keeps to themselves.",
        "after_ko": "won't say a word about it.",
        "rematch": "won't initiate a rematch.",
    }
}